<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="25" passed="3" failed="1" skipped="21">
  <reporter-output>
    <line>
      <![CDATA[<b></b> <br />]]>
    </line>
    <line>
      <![CDATA[<b>Searching for Order ID DR-46913</b> <br />]]>
    </line>
    <line>
      <![CDATA[<b></b> <br />]]>
    </line>
    <line>
      <![CDATA[<b>Checking pre-order checks</b> <br />]]>
    </line>
    <line>
      <![CDATA[<b>Started verifying monthly payment does not change after editing the basic cash price</b> <br />]]>
    </line>
    <line>
      <![CDATA[<b>Monthly payment Before Editing the Cash Price is 1565.98</b> <br />]]>
    </line>
    <line>
      <![CDATA[<b>Vehicle's Basic Cash Price Changed to 60,000</b> <br />]]>
    </line>
    <line>
      <![CDATA[<b>Now Getting the Monthly payment from customer contract tab</b> <br />]]>
    </line>
    <line>
      <![CDATA[<b>Monthly payment After Editing the Cash Price is 1565.98</b> <br />]]>
    </line>
    <line>
      <![CDATA[<b>Verified that monthly payment does not change after editing the basic cash price</b> <br />]]>
    </line>
    <line>
      <![CDATA[<b></b> <br />]]>
    </line>
    <line>
      <![CDATA[<b>Writing Holding Cost Summary values to excel has been completed</b> <br />]]>
    </line>
    <line>
      <![CDATA[<b>Actual and Expected Message do not matches, hence test failed</b> <br />]]>
    </line>
    <line>
      <![CDATA[<br>----------Screenshot---------<br>]]>
    </line>
    <line>
      <![CDATA[<img src="D:\Orders_Vehicles\AMT_Orders_Vehicles\target\surefire-reports\html\failure_screenshots\T4_verify_that_same_funder_with_same_term_and_mileage_can_not_be_added_for_with_customer_flow_test_10_01_2024_07_18_23.png" height="800" width="1000">]]>
    </line>
  </reporter-output>
  <suite started-at="2024-01-10T19:14:59 IST" name="Default suite" finished-at="2024-01-10T19:18:23 IST" duration-ms="204649">
    <groups>
    </groups>
    <test started-at="2024-01-10T19:14:59 IST" name="Default test" finished-at="2024-01-10T19:18:23 IST" duration-ms="204649">
      <class name="orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test">
        <test-method is-config="true" signature="start_info()[pri:0, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0]" started-at="2024-01-10T19:14:59 IST" name="start_info" finished-at="2024-01-10T19:14:59 IST" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start_info -->
        <test-method is-config="true" signature="setup()[pri:0, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0]" started-at="2024-01-10T19:14:59 IST" name="setup" finished-at="2024-01-10T19:15:25 IST" duration-ms="26169" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="T1_open_order_created_in_acquisition_test()[pri:1, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0]" started-at="2024-01-10T19:15:25 IST" name="T1_open_order_created_in_acquisition_test" finished-at="2024-01-10T19:16:31 IST" duration-ms="65990" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[<b></b> <br />]]>
            </line>
            <line>
              <![CDATA[<b>Searching for Order ID DR-46913</b> <br />]]>
            </line>
          </reporter-output>
        </test-method> <!-- T1_open_order_created_in_acquisition_test -->
        <test-method signature="T2_pre_order_pass_check_in_customer_contract_tab_test()[pri:2, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0]" started-at="2024-01-10T19:16:31 IST" name="T2_pre_order_pass_check_in_customer_contract_tab_test" finished-at="2024-01-10T19:16:48 IST" depends-on-methods="orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T1_open_order_created_in_acquisition_test" duration-ms="17568" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[<b></b> <br />]]>
            </line>
            <line>
              <![CDATA[<b>Checking pre-order checks</b> <br />]]>
            </line>
          </reporter-output>
        </test-method> <!-- T2_pre_order_pass_check_in_customer_contract_tab_test -->
        <test-method signature="T3_verify_that_editing_the_basic_cash_price_does_not_affect_the_monthly_payment_on_customer_contract_tab_test()[pri:3, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0]" started-at="2024-01-10T19:16:48 IST" name="T3_verify_that_editing_the_basic_cash_price_does_not_affect_the_monthly_payment_on_customer_contract_tab_test" finished-at="2024-01-10T19:17:54 IST" depends-on-methods="orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T2_pre_order_pass_check_in_customer_contract_tab_test" duration-ms="65728" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[<b>Started verifying monthly payment does not change after editing the basic cash price</b> <br />]]>
            </line>
            <line>
              <![CDATA[<b>Monthly payment Before Editing the Cash Price is 1565.98</b> <br />]]>
            </line>
            <line>
              <![CDATA[<b>Vehicle's Basic Cash Price Changed to 60,000</b> <br />]]>
            </line>
            <line>
              <![CDATA[<b>Now Getting the Monthly payment from customer contract tab</b> <br />]]>
            </line>
            <line>
              <![CDATA[<b>Monthly payment After Editing the Cash Price is 1565.98</b> <br />]]>
            </line>
            <line>
              <![CDATA[<b>Verified that monthly payment does not change after editing the basic cash price</b> <br />]]>
            </line>
          </reporter-output>
        </test-method> <!-- T3_verify_that_editing_the_basic_cash_price_does_not_affect_the_monthly_payment_on_customer_contract_tab_test -->
        <test-method signature="T4_verify_that_same_funder_with_same_term_and_mileage_can_not_be_added_for_with_customer_flow_test(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:4, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0]" started-at="2024-01-10T19:17:55 IST" name="T4_verify_that_same_funder_with_same_term_and_mileage_can_not_be_added_for_with_customer_flow_test" data-provider="testData1" finished-at="2024-01-10T19:18:23 IST" depends-on-methods="orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T3_verify_that_editing_the_basic_cash_price_does_not_affect_the_monthly_payment_on_customer_contract_tab_test" duration-ms="28202" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[REF001]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[05/12/26]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[33]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[5000]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[1000]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[200]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[12]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[500]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[6000]]>
              </value>
            </param>
            <param index="9">
              <value>
                <![CDATA[20]]>
              </value>
            </param>
            <param index="10">
              <value>
                <![CDATA[HPNR (Formula 3) - HPNR]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T4_verify_that_same_funder_with_same_term_and_mileage_can_not_be_added_for_with_customer_flow_test(Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.java:93)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<b></b> <br />]]>
            </line>
            <line>
              <![CDATA[<b>Writing Holding Cost Summary values to excel has been completed</b> <br />]]>
            </line>
            <line>
              <![CDATA[<b>Actual and Expected Message do not matches, hence test failed</b> <br />]]>
            </line>
            <line>
              <![CDATA[<br>----------Screenshot---------<br>]]>
            </line>
            <line>
              <![CDATA[<img src="D:\Orders_Vehicles\AMT_Orders_Vehicles\target\surefire-reports\html\failure_screenshots\T4_verify_that_same_funder_with_same_term_and_mileage_can_not_be_added_for_with_customer_flow_test_10_01_2024_07_18_23.png" height="800" width="1000">]]>
            </line>
          </reporter-output>
        </test-method> <!-- T4_verify_that_same_funder_with_same_term_and_mileage_can_not_be_added_for_with_customer_flow_test -->
        <test-method signature="T5_verify_that_deselecting_the_selected_funder_does_not_affect_the_monthly_payment_on_customer_contract_tab_test()[pri:5, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0]" started-at="2024-01-10T19:18:23 IST" name="T5_verify_that_deselecting_the_selected_funder_does_not_affect_the_monthly_payment_on_customer_contract_tab_test" finished-at="2024-01-10T19:18:23 IST" depends-on-methods="orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T4_verify_that_same_funder_with_same_term_and_mileage_can_not_be_added_for_with_customer_flow_test" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T5_verify_that_deselecting_the_selected_funder_does_not_affect_the_monthly_payment_on_customer_contract_tab_test()[pri:5, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T5_verify_that_deselecting_the_selected_funder_does_not_affect_the_monthly_payment_on_customer_contract_tab_test()[pri:5, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- T5_verify_that_deselecting_the_selected_funder_does_not_affect_the_monthly_payment_on_customer_contract_tab_test -->
        <test-method signature="T6_verify_default_order_status_vehicle_tab_test()[pri:6, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0]" started-at="2024-01-10T19:18:23 IST" name="T6_verify_default_order_status_vehicle_tab_test" finished-at="2024-01-10T19:18:23 IST" depends-on-methods="orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T5_verify_that_deselecting_the_selected_funder_does_not_affect_the_monthly_payment_on_customer_contract_tab_test" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T6_verify_default_order_status_vehicle_tab_test()[pri:6, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T6_verify_default_order_status_vehicle_tab_test()[pri:6, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- T6_verify_default_order_status_vehicle_tab_test -->
        <test-method signature="T7_verify_order_status_after_uploading_order_form_in_vehicle_tab_test()[pri:7, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0]" started-at="2024-01-10T19:18:23 IST" name="T7_verify_order_status_after_uploading_order_form_in_vehicle_tab_test" finished-at="2024-01-10T19:18:23 IST" depends-on-methods="orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T6_verify_default_order_status_vehicle_tab_test" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T7_verify_order_status_after_uploading_order_form_in_vehicle_tab_test()[pri:7, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T7_verify_order_status_after_uploading_order_form_in_vehicle_tab_test()[pri:7, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- T7_verify_order_status_after_uploading_order_form_in_vehicle_tab_test -->
        <test-method signature="T8_verify_default_payment_status_on_vehicle_tab_test()[pri:8, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0]" started-at="2024-01-10T19:18:23 IST" name="T8_verify_default_payment_status_on_vehicle_tab_test" finished-at="2024-01-10T19:18:23 IST" depends-on-methods="orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T7_verify_order_status_after_uploading_order_form_in_vehicle_tab_test" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T8_verify_default_payment_status_on_vehicle_tab_test()[pri:8, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T8_verify_default_payment_status_on_vehicle_tab_test()[pri:8, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- T8_verify_default_payment_status_on_vehicle_tab_test -->
        <test-method signature="T9_verify_payment_status_after_selecting_payment_sent_date_on_vehicle_tab_test()[pri:9, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0]" started-at="2024-01-10T19:18:23 IST" name="T9_verify_payment_status_after_selecting_payment_sent_date_on_vehicle_tab_test" finished-at="2024-01-10T19:18:23 IST" depends-on-methods="orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T8_verify_default_payment_status_on_vehicle_tab_test" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T9_verify_payment_status_after_selecting_payment_sent_date_on_vehicle_tab_test()[pri:9, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T9_verify_payment_status_after_selecting_payment_sent_date_on_vehicle_tab_test()[pri:9, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- T9_verify_payment_status_after_selecting_payment_sent_date_on_vehicle_tab_test -->
        <test-method signature="T10_verify_payment_status_should_be_reversed_to_payment_required_after_selecting_payment_by_AMT_on_vehicle_tab_test()[pri:10, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0]" started-at="2024-01-10T19:18:23 IST" name="T10_verify_payment_status_should_be_reversed_to_payment_required_after_selecting_payment_by_AMT_on_vehicle_tab_test" finished-at="2024-01-10T19:18:23 IST" depends-on-methods="orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T9_verify_payment_status_after_selecting_payment_sent_date_on_vehicle_tab_test" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T10_verify_payment_status_should_be_reversed_to_payment_required_after_selecting_payment_by_AMT_on_vehicle_tab_test()[pri:10, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T10_verify_payment_status_should_be_reversed_to_payment_required_after_selecting_payment_by_AMT_on_vehicle_tab_test()[pri:10, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- T10_verify_payment_status_should_be_reversed_to_payment_required_after_selecting_payment_by_AMT_on_vehicle_tab_test -->
        <test-method signature="T11_verify_payment_status_after_selecting_payment_sent_date_for_amount_due_on_vehicle_tab_test()[pri:11, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0]" started-at="2024-01-10T19:18:23 IST" name="T11_verify_payment_status_after_selecting_payment_sent_date_for_amount_due_on_vehicle_tab_test" finished-at="2024-01-10T19:18:23 IST" depends-on-methods="orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T10_verify_payment_status_should_be_reversed_to_payment_required_after_selecting_payment_by_AMT_on_vehicle_tab_test" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T11_verify_payment_status_after_selecting_payment_sent_date_for_amount_due_on_vehicle_tab_test()[pri:11, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T11_verify_payment_status_after_selecting_payment_sent_date_for_amount_due_on_vehicle_tab_test()[pri:11, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- T11_verify_payment_status_after_selecting_payment_sent_date_for_amount_due_on_vehicle_tab_test -->
        <test-method signature="T12_verify_default_status_acceptance_conditions_for_ownbook_hire_flow()[pri:12, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0]" started-at="2024-01-10T19:18:23 IST" name="T12_verify_default_status_acceptance_conditions_for_ownbook_hire_flow" finished-at="2024-01-10T19:18:23 IST" depends-on-methods="orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T11_verify_payment_status_after_selecting_payment_sent_date_for_amount_due_on_vehicle_tab_test" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T12_verify_default_status_acceptance_conditions_for_ownbook_hire_flow()[pri:12, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T12_verify_default_status_acceptance_conditions_for_ownbook_hire_flow()[pri:12, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- T12_verify_default_status_acceptance_conditions_for_ownbook_hire_flow -->
        <test-method signature="T13_verify_summary_section_values()[pri:13, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0]" started-at="2024-01-10T19:18:23 IST" name="T13_verify_summary_section_values" finished-at="2024-01-10T19:18:23 IST" depends-on-methods="orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T12_verify_default_status_acceptance_conditions_for_ownbook_hire_flow" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T13_verify_summary_section_values()[pri:13, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T13_verify_summary_section_values()[pri:13, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- T13_verify_summary_section_values -->
        <test-method signature="T14_verify_payment_default_status()[pri:14, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0]" started-at="2024-01-10T19:18:23 IST" name="T14_verify_payment_default_status" finished-at="2024-01-10T19:18:23 IST" depends-on-methods="orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T13_verify_summary_section_values" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T14_verify_payment_default_status()[pri:14, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T14_verify_payment_default_status()[pri:14, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- T14_verify_payment_default_status -->
        <test-method signature="T15_make_payment_with_new_payment()[pri:15, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0]" started-at="2024-01-10T19:18:23 IST" name="T15_make_payment_with_new_payment" finished-at="2024-01-10T19:18:23 IST" depends-on-methods="orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T14_verify_payment_default_status" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T15_make_payment_with_new_payment()[pri:15, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T15_make_payment_with_new_payment()[pri:15, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- T15_make_payment_with_new_payment -->
        <test-method signature="T17_verify_delivery_status_after_selecting_date_offered_in_delivery_section_of_customer_contract_tab_test()[pri:17, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0]" started-at="2024-01-10T19:18:23 IST" name="T17_verify_delivery_status_after_selecting_date_offered_in_delivery_section_of_customer_contract_tab_test" finished-at="2024-01-10T19:18:23 IST" depends-on-methods="orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T16_verify_payment_status_after_making_a_payment_on_customer_contract_tab" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T17_verify_delivery_status_after_selecting_date_offered_in_delivery_section_of_customer_contract_tab_test()[pri:17, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T17_verify_delivery_status_after_selecting_date_offered_in_delivery_section_of_customer_contract_tab_test()[pri:17, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- T17_verify_delivery_status_after_selecting_date_offered_in_delivery_section_of_customer_contract_tab_test -->
        <test-method signature="T16_verify_payment_status_after_making_a_payment_on_customer_contract_tab()[pri:16, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0]" started-at="2024-01-10T19:18:23 IST" name="T16_verify_payment_status_after_making_a_payment_on_customer_contract_tab" finished-at="2024-01-10T19:18:23 IST" depends-on-methods="orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T15_make_payment_with_new_payment" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T16_verify_payment_status_after_making_a_payment_on_customer_contract_tab()[pri:16, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T16_verify_payment_status_after_making_a_payment_on_customer_contract_tab()[pri:16, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- T16_verify_payment_status_after_making_a_payment_on_customer_contract_tab -->
        <test-method signature="T18_verify_delivery_status_after_selecting_confirmed_delivery_date_in_delivery_section_of_customer_contract_test()[pri:18, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0]" started-at="2024-01-10T19:18:23 IST" name="T18_verify_delivery_status_after_selecting_confirmed_delivery_date_in_delivery_section_of_customer_contract_test" finished-at="2024-01-10T19:18:23 IST" depends-on-methods="orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T17_verify_delivery_status_after_selecting_date_offered_in_delivery_section_of_customer_contract_tab_test" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T18_verify_delivery_status_after_selecting_confirmed_delivery_date_in_delivery_section_of_customer_contract_test()[pri:18, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T18_verify_delivery_status_after_selecting_confirmed_delivery_date_in_delivery_section_of_customer_contract_test()[pri:18, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- T18_verify_delivery_status_after_selecting_confirmed_delivery_date_in_delivery_section_of_customer_contract_test -->
        <test-method signature="T19_verify_delivery_status_after_uploading_delivery_note_in_post_delivery_section_on_customer_contract_tab_test()[pri:19, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0]" started-at="2024-01-10T19:18:23 IST" name="T19_verify_delivery_status_after_uploading_delivery_note_in_post_delivery_section_on_customer_contract_tab_test" finished-at="2024-01-10T19:18:23 IST" depends-on-methods="orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T18_verify_delivery_status_after_selecting_confirmed_delivery_date_in_delivery_section_of_customer_contract_test" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T19_verify_delivery_status_after_uploading_delivery_note_in_post_delivery_section_on_customer_contract_tab_test()[pri:19, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T19_verify_delivery_status_after_uploading_delivery_note_in_post_delivery_section_on_customer_contract_tab_test()[pri:19, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- T19_verify_delivery_status_after_uploading_delivery_note_in_post_delivery_section_on_customer_contract_tab_test -->
        <test-method signature="T20_verify_delivery_status_on_customer_contract_tab_and_vehicle_order_tab_are_same_when_deliver_to_customer_toggle_button_in_on_test()[pri:20, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0]" started-at="2024-01-10T19:18:23 IST" name="T20_verify_delivery_status_on_customer_contract_tab_and_vehicle_order_tab_are_same_when_deliver_to_customer_toggle_button_in_on_test" finished-at="2024-01-10T19:18:23 IST" depends-on-methods="orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T19_verify_delivery_status_after_uploading_delivery_note_in_post_delivery_section_on_customer_contract_tab_test" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T20_verify_delivery_status_on_customer_contract_tab_and_vehicle_order_tab_are_same_when_deliver_to_customer_toggle_button_in_on_test()[pri:20, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T20_verify_delivery_status_on_customer_contract_tab_and_vehicle_order_tab_are_same_when_deliver_to_customer_toggle_button_in_on_test()[pri:20, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- T20_verify_delivery_status_on_customer_contract_tab_and_vehicle_order_tab_are_same_when_deliver_to_customer_toggle_button_in_on_test -->
        <test-method signature="T21_verify_payout_pack_statuses_on_customer_contract_tab_test()[pri:21, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0]" started-at="2024-01-10T19:18:23 IST" name="T21_verify_payout_pack_statuses_on_customer_contract_tab_test" finished-at="2024-01-10T19:18:23 IST" depends-on-methods="orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T20_verify_delivery_status_on_customer_contract_tab_and_vehicle_order_tab_are_same_when_deliver_to_customer_toggle_button_in_on_test" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T21_verify_payout_pack_statuses_on_customer_contract_tab_test()[pri:21, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T21_verify_payout_pack_statuses_on_customer_contract_tab_test()[pri:21, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- T21_verify_payout_pack_statuses_on_customer_contract_tab_test -->
        <test-method signature="T22_verify_delivery_section_gets_enabled_when_deliver_to_customer_toggle_button_is_made_off_test()[pri:22, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0]" started-at="2024-01-10T19:18:23 IST" name="T22_verify_delivery_section_gets_enabled_when_deliver_to_customer_toggle_button_is_made_off_test" finished-at="2024-01-10T19:18:23 IST" depends-on-methods="orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T21_verify_payout_pack_statuses_on_customer_contract_tab_test" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T22_verify_delivery_section_gets_enabled_when_deliver_to_customer_toggle_button_is_made_off_test()[pri:22, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T22_verify_delivery_section_gets_enabled_when_deliver_to_customer_toggle_button_is_made_off_test()[pri:22, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- T22_verify_delivery_section_gets_enabled_when_deliver_to_customer_toggle_button_is_made_off_test -->
        <test-method signature="T23_verify_delivery_status_after_selecting_date_offered_in_delivery_section_of_vehicle_order_tab_test()[pri:23, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0]" started-at="2024-01-10T19:18:23 IST" name="T23_verify_delivery_status_after_selecting_date_offered_in_delivery_section_of_vehicle_order_tab_test" finished-at="2024-01-10T19:18:23 IST" depends-on-methods="orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T22_verify_delivery_section_gets_enabled_when_deliver_to_customer_toggle_button_is_made_off_test" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T23_verify_delivery_status_after_selecting_date_offered_in_delivery_section_of_vehicle_order_tab_test()[pri:23, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T23_verify_delivery_status_after_selecting_date_offered_in_delivery_section_of_vehicle_order_tab_test()[pri:23, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- T23_verify_delivery_status_after_selecting_date_offered_in_delivery_section_of_vehicle_order_tab_test -->
        <test-method signature="T24_verify_delivery_status_after_selecting_confirmed_delivery_date_in_delivery_section_of_vehicle_tab_test()[pri:24, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0]" started-at="2024-01-10T19:18:23 IST" name="T24_verify_delivery_status_after_selecting_confirmed_delivery_date_in_delivery_section_of_vehicle_tab_test" finished-at="2024-01-10T19:18:23 IST" depends-on-methods="orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T23_verify_delivery_status_after_selecting_date_offered_in_delivery_section_of_vehicle_order_tab_test" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T24_verify_delivery_status_after_selecting_confirmed_delivery_date_in_delivery_section_of_vehicle_tab_test()[pri:24, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T24_verify_delivery_status_after_selecting_confirmed_delivery_date_in_delivery_section_of_vehicle_tab_test()[pri:24, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- T24_verify_delivery_status_after_selecting_confirmed_delivery_date_in_delivery_section_of_vehicle_tab_test -->
        <test-method signature="T25_verify_delivery_status_after_uploading_delivery_note_in_post_delivery_section_on_vehicle_order_tab_test()[pri:25, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0]" started-at="2024-01-10T19:18:23 IST" name="T25_verify_delivery_status_after_uploading_delivery_note_in_post_delivery_section_on_vehicle_order_tab_test" finished-at="2024-01-10T19:18:23 IST" depends-on-methods="orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T24_verify_delivery_status_after_selecting_confirmed_delivery_date_in_delivery_section_of_vehicle_tab_test" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T25_verify_delivery_status_after_uploading_delivery_note_in_post_delivery_section_on_vehicle_order_tab_test()[pri:25, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test.T25_verify_delivery_status_after_uploading_delivery_note_in_post_delivery_section_on_vehicle_order_tab_test()[pri:25, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- T25_verify_delivery_status_after_uploading_delivery_note_in_post_delivery_section_on_vehicle_order_tab_test -->
        <test-method is-config="true" signature="end()[pri:0, instance:orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test@543295b0]" started-at="2024-01-10T19:18:23 IST" name="end" finished-at="2024-01-10T19:18:23 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
      </class> <!-- orders.Orders_Verify_ownbook_business_hire_funder_With_Customer_Flow_Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
