<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DSK-4052" failures="1" tests="8" name="orders.Orders_Asset_Funding_Required_Flow_FL_BCH_with_funder_with_maintenance_Test" time="155.252" errors="1" timestamp="2023-10-20T16:03:41 IST" skipped="0">
  <testcase classname="orders.Orders_Asset_Funding_Required_Flow_FL_BCH_with_funder_with_maintenance_Test" name="open_order_created_in_acquisition_test" time="57.499"/>
  <system-out>
    <![CDATA[<b>Searching for Order ID OD-95584</b> <br />]]>
  </system-out>
  <testcase classname="orders.Orders_Asset_Funding_Required_Flow_FL_BCH_with_funder_with_maintenance_Test" name="verify_default_status_required_flow_test" time="11.534"/>
  <system-out>
    <![CDATA[<b></b> <br />
<b>Started verifying Default Status for BCH required flow</b> <br />
<b>Default Status for BCH required flow Found OK i.e Quote Accepted because Funder is already added from acquisition quote</b> <br />]]>
  </system-out>
  <testcase classname="orders.Orders_Asset_Funding_Required_Flow_FL_BCH_with_funder_with_maintenance_Test" name="verify_default_funder_is_not_deleted_test" time="2.156"/>
  <system-out>
    <![CDATA[<b></b> <br />
<b>Trying to delete funder</b> <br />
<b>Default funder can not be deleted as Delete button for selected funder is not enabled</b> <br />]]>
  </system-out>
  <testcase classname="orders.Orders_Asset_Funding_Required_Flow_FL_BCH_with_funder_with_maintenance_Test" name="verify_selected_funder_can_not_be_edited_test" time="0.256"/>
  <system-out>
    <![CDATA[<b></b> <br />
<b>Trying to edit the selected funder</b> <br />
<b>Double Clicked on selected funder and we got warning message : A selected funder cannot be edited. Please remove funder selection before editing</b> <br />
<b>Selected funder can not be edited</b> <br />]]>
  </system-out>
  <testcase classname="orders.Orders_Asset_Funding_Required_Flow_FL_BCH_with_funder_with_maintenance_Test" name="verify_holding_cost_after_deselecting_funder_test" time="18.959"/>
  <system-out>
    <![CDATA[<b></b> <br />
<b>De-selecting funder</b> <br />
<b>Now verifying the holding cost based on ownbook after de-selecting funder</b> <br />
<b>Actual Holding cost based on ownbook after de-selecting funder is 929.36</b> <br />
<b>Expected Holding cost based on ownbook after de-selecting funder is 929.36</b> <br />
<b>Holding cost based on ownbook after de-selecting funder found OK</b> <br />]]>
  </system-out>
  <testcase classname="orders.Orders_Asset_Funding_Required_Flow_FL_BCH_with_funder_with_maintenance_Test" name="verify_holding_cost_without_maintenance_based_on_ownbook_calculation_test" time="7.357"/>
  <system-out>
    <![CDATA[<b></b> <br />
<b>Making Cap Maint toggle button off and verifying Holding Cost</b> <br />
<b>Now verifying the holding cost based on ownbook</b> <br />
<b>Actual Holding cost based on ownbook is 900.75</b> <br />
<b>Expected Holding cost based on ownbook 900.75</b> <br />
<b>Holding cost based on ownbook found OK</b> <br />]]>
  </system-out>
  <testcase classname="orders.Orders_Asset_Funding_Required_Flow_FL_BCH_with_funder_with_maintenance_Test" name="verify_funder_is_deselected_after_selecting_the_other_matrix_cell_test" time="13.734">
    <error message="no such element: No node with given id found
  (Session info: chrome=118.0.5993.72)
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: &#039;4.1.0&#039;, revision: &#039;87802e897b&#039;
System info: host: &#039;DSK-4052&#039;, ip: &#039;172.16.1.80&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;19.0.1&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [52fdce7bb39c66bd87dcf9fb5799ec90, getElementAttribute {id=85D5DCB0B2E7A88C49CD2F35DE60139D_element_1003, name=class}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 118.0.5993.72, chrome: {chromedriverVersion: 118.0.5993.70 (e52f33f30b91..., userDataDir: C:\Users\NITEIN~1.KUR\AppDa...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:63219}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:63219/devtoo..., se:cdpVersion: 118.0.5993.72, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on WINDOWS (52fdce7bb39c66bd87dcf9fb5799ec90)] -&gt; xpath: //*[contains(@class, &#039;rTableCell&#039;)]]
Session ID: 52fdce7bb39c66bd87dcf9fb5799ec90" type="org.openqa.selenium.NoSuchElementException">
      <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: No node with given id found
  (Session info: chrome=118.0.5993.72)
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.1.0', revision: '87802e897b'
System info: host: 'DSK-4052', ip: '172.16.1.80', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '19.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [52fdce7bb39c66bd87dcf9fb5799ec90, getElementAttribute {id=85D5DCB0B2E7A88C49CD2F35DE60139D_element_1003, name=class}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 118.0.5993.72, chrome: {chromedriverVersion: 118.0.5993.70 (e52f33f30b91..., userDataDir: C:\Users\NITEIN~1.KUR\AppDa...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:63219}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:63219/devtoo..., se:cdpVersion: 118.0.5993.72, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on WINDOWS (52fdce7bb39c66bd87dcf9fb5799ec90)] -> xpath: //*[contains(@class, 'rTableCell')]]
Session ID: 52fdce7bb39c66bd87dcf9fb5799ec90
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:164)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:139)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:559)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:251)
at org.openqa.selenium.remote.RemoteWebElement.getAttribute(RemoteWebElement.java:152)
at com.amt.pages.AssetFundingPage.verify_funder_is_deselected_after_selecting_the_other_matrix_cell(AssetFundingPage.java:1919)
at orders.Orders_Asset_Funding_Required_Flow_FL_BCH_with_funder_with_maintenance_Test.verify_funder_is_deselected_after_selecting_the_other_matrix_cell_test(Orders_Asset_Funding_Required_Flow_FL_BCH_with_funder_with_maintenance_Test.java:104)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verify_funder_is_deselected_after_selecting_the_other_matrix_cell_test -->
  <system-out>
    <![CDATA[<b></b> <br />
<b>Selecting the funder</b> <br />
<b>Selecting the other cell from Holding cost matrix</b> <br />
<b>Now verifying that the funder is de-selected</b> <br />
<b>Verified that the funder is de-selected after selecting ownbook matrix other cell --Found OK</b> <br />
<br>----------Screenshot---------<br>
<img src="D:\Orders_Vehicles\AMT_Orders_Vehicles\target\surefire-reports\html\failure_screenshots\verify_funder_is_deselected_after_selecting_the_other_matrix_cell_test_20_10_2023_04_02_57.png" height="800" width="1000">]]>
  </system-out>
  <testcase classname="orders.Orders_Asset_Funding_Required_Flow_FL_BCH_with_funder_with_maintenance_Test" name="verify_document_is_uploaded_in_funder_test" time="43.757">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at orders.Orders_Asset_Funding_Required_Flow_FL_BCH_with_funder_with_maintenance_Test.verify_document_is_uploaded_in_funder_test(Orders_Asset_Funding_Required_Flow_FL_BCH_with_funder_with_maintenance_Test.java:118)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verify_document_is_uploaded_in_funder_test -->
  <system-out>
    <![CDATA[<b></b> <br />
<b>Trying to upload doc in funder</b> <br />
<b>Warning : Document in funder is not uploaded</b> <br />
<br>----------Screenshot---------<br>
<img src="D:\Orders_Vehicles\AMT_Orders_Vehicles\target\surefire-reports\html\failure_screenshots\verify_document_is_uploaded_in_funder_test_20_10_2023_04_03_41.png" height="800" width="1000">]]>
  </system-out>
</testsuite> <!-- orders.Orders_Asset_Funding_Required_Flow_FL_BCH_with_funder_with_maintenance_Test -->
